// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (Intellectus).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file dds_TestCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool int2ddsgen (version: 4.1.0).
 */

#ifndef INT2_DDS_GENERATED__DDS_TESTCDRAUX_HPP
#define INT2_DDS_GENERATED__DDS_TESTCDRAUX_HPP

#include "dds_Test.hpp"

constexpr uint32_t Image_max_cdr_typesize {276UL};
constexpr uint32_t Image_max_key_cdr_typesize {0UL};


namespace intellectus {
namespace int2cdr {

class Cdr;
class CdrSizeCalculator;

Intellectus_user_DllExport void serialize_key(
        intellectus::int2cdr::Cdr& scdr,
        const Image& data);


} // namespace int2cdr
} // namespace intellectus

#endif // INT2_DDS_GENERATED__DDS_TESTCDRAUX_HPP

